using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace BluetoothBarcodeReader.Scanner
{
    enum Symbology
    {
        UPC_E0,
        UPC_E1,
        UPC_A,
        MSI_PLESSEY,
        EAN_8,
        EAN_13,
        CODABAR,
        CODE39,
        D2O5,
        I205,
        CODE11,
        CODE93,
        CODE128,
        PDF417,
        I2O5,
        UCC128,
        BOOKLAND,
        TRIOPTIC,
        RFID,
        MAGSTRIPE,
        UPCEAN_SUPP,
        CODE32,
        ISBT128,
        COUPON,
        MICROP417,
        MACROP417,
        MAXICODE,
        DATAMATRIX,
        QRCODE,
        MACROMICROP417,
        GS1,
        GS1LIMITED,
        GS1EXPAND,
        WEBCODE,
        CUECAT,
        COMP_ABC,
        TCIF_CODE39,
        USPS_POSTNET,
        USPS_PLANET,
        POSTAL_UK,
        POSTAL_JP,
        POSTAL_AU,
        POSTAL_NL,
        POSTAL_CA,
        AZTEC,
        AZTEC_MESA,
        CODE49,
        OPT_CHAR_RECOG,
        CODABLOCK,
        MATRIX2O5,
        PLESSEY,
        POSTAL_CH,
        POSTAL_KR,
        TELEPEN,
        CODE16K,
        POSICODE,
        USPS_INTMAIL,
        UNKNOWN,
        NULL,
        INVALID
    }
}
